<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Platforms>x64;x86</Platforms>
    <Version>1.0.3.4</Version>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IdentityModel" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\iParkingv5.Objects\iParkingv5.Objects.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Kztek.Tool">
      <HintPath>G:\1.DeployTest\XC\net6.0-windows\Kztek.Tool.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
