<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\iParkingv5.Lpr\iParkingv5.Lpr.csproj" />
    <ProjectReference Include="..\libs\Object\1.Source\Kztek.Object.Entity\Kztek.Object.Entity.csproj" />
  </ItemGroup>

</Project>
