<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>8.0.0.7</Version>
		<Authors>KZTEK</Authors>
		<Company>KZTEK</Company>
		<Description>KZTEK</Description>
		<Copyright>KZTEK</Copyright>
		<PackageProjectUrl>https://kztek.net/</PackageProjectUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RestSharp" Version="112.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\iParkingv8.Object\iParkingv8.Object.csproj" />
		<ProjectReference Include="..\libs\Api\1.Source\Kztek.Api\Kztek.Api.csproj" />
		<ProjectReference Include="..\libs\Object\1.Source\Kztek.Object.Entity\Kztek.Object.Entity.csproj" />
		<ProjectReference Include="..\libs\Tool\1.Source\Kztek.Tool\Kztek.Tool.csproj" />
	</ItemGroup>

</Project>
